#! /bin/bash

case $1 in
    "-a" | "--add")
    while IFS= read -r line || [ -n "$line" ];
    do
        ## -m creates a home directory
        useradd -m $line
    done < $2
    ;;

    "-d" | "--delete")
    while IFS= read -r line || [ -n "$line" ];
    do
        ## -r deletes the home directory
        userdel -r $line
    done < $2
    ;;

    "-l" | "--list")
    while IFS= read -r line || [ -n "$line" ];
    do
        ## display the file, searched for the name
        cat /etc/passwd | grep $line
    done < $2
    ;;

    ## Default if no flag or unkown flag is given
    *)
    echo Unkown command
    ;;
esac